import React from 'react';
import { Container, Typography, Box, Link } from '@mui/material';

const PrivacyPolicy = () => {
  return (
    <Container maxWidth="md">
      <Box sx={{ color: 'white', my: 4 }}>
        <Typography variant="h4" component="h1" gutterBottom color="inherit">
          Unofficial Privacy Policy
        </Typography>

        <Typography variant="h6" gutterBottom color="inherit">
          Independence Statement
        </Typography>
        <Typography paragraph color="inherit">
          This application is an independent project. It is not affiliated with, endorsed by, or connected to any major tech companies or AI organizations. This includes, but is not limited to, Midjourney, OpenAI, Google, and Amazon.
        </Typography>

        <Typography variant="h6" gutterBottom color="inherit">
          Disclaimer on Results
        </Typography>
        <Typography paragraph color="inherit">
          While we strive to provide useful and creative prompts, we cannot guarantee specific outcomes. The nature of AI art generation means results can vary widely. We encourage you to experiment with the prompts, as they often lead to interesting and unexpected results.
        </Typography>

        <Typography variant="h6" gutterBottom color="inherit">
          Intended Use
        </Typography>
        <Typography paragraph color="inherit">
          This application is designed for creating art prompts to be used with AI art generation tools. We hope you'll use it to explore your creativity and produce unique artwork.
        </Typography>

        <Typography variant="h6" gutterBottom color="inherit">
          Restrictions on Use
        </Typography>
        <Typography paragraph color="inherit">
          Please do not use this application for:
        </Typography>
        <ul style={{ color: 'white' }}>
          <li>Attempting to bypass AI content filters or protections</li>
          <li>Generating content related to illegal activities</li>
          <li>Creating harmful or malicious content</li>
          <li>Any purpose that could infringe on the rights of others</li>
        </ul>

        <Typography variant="h6" gutterBottom color="inherit">
          Legal Notice
        </Typography>
        <Typography paragraph color="inherit">
          This privacy policy is written in plain language and is not a comprehensive legal document. While we've made efforts to cover key points, it may not address all legal aspects related to the use of this application.
        </Typography>

        <Typography variant="h6" gutterBottom color="inherit">
          Responsibility
        </Typography>
        <Typography paragraph color="inherit">
          Users are responsible for how they use the prompts generated by this application. We trust that you will use this tool responsibly and creatively.
        </Typography>

        <Typography variant="h6" gutterBottom color="inherit">
          Updates and Changes
        </Typography>
        <Typography paragraph color="inherit">
          We may update this policy from time to time. Any significant changes will be communicated through the application.
        </Typography>

        <Typography variant="h6" gutterBottom color="inherit">
          Contact Information
        </Typography>
        <Typography paragraph color="inherit">
          If you have any questions about this policy or the application, please contact us at: <Link href="mailto:contact@example.com" color="inherit">contact@example.com</Link>
        </Typography>

        <Typography paragraph color="inherit">
          Remember, the goal of this application is to assist in creating great AI-generated art. We hope you enjoy using it and find it valuable in your creative process.
        </Typography>
      </Box>
    </Container>
  );
};

export default PrivacyPolicy;